### ISSUE TITLE
no context?

### ISSUE THREAD

**Issue by hailiang-wang** [kite1988/nus-sms-corpus#1]
great jobs! But for each message, is it possible to get its reply or what message does it reply to? In this way, make it a real conversation.

**Comment by knmnyn** [comment]
Hi Hain Wang:

The corpus doesn't carry this information explicitly.  In certain cases,
where the messages are linked by the same sender as recipient and vice
versa, you may be able to infer a reply relation.  Unfortunately, the
metadata in our corpus and in the submissions does not allow us to infer
this exact relation, for privacy reason (a submitter could scrub out some
sensitive replies that they did not want to appear in the corpus).


Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by hailiang-wang** [comment]
Got it, thanks.
